sudo: required

language: C

install: sudo apt-get install autotools-dev

services:
  - docker

script:
  - ./configure && make
  - tests/test1.sh

after_success:
  - docker build -t mjeromin/ci-testing .
  - docker run -d mjeromin/ci-testing "/bin/helloworld"

notifications:
  email:
    recipients:
      - mark.jeromin@sysfrog.net
    on_success: never
    on_failure: always
