language: C
install: sudo apt-get install autotools-dev
script:
  - ./configure && make
  - tests/test1.sh
notifications:
  email:
    recipients:
      - mark.jeromin@sysfrog.net
    on_success: never
    on_failure: always
