language: C
script:
  - ./configure && make
  - tests/test1.sh
  - tests/test2.sh
notifications:
  email:
    recipients:
      - mark.jeromin@sysfrog.net
    on_success: never
    on_failure: always
